[package]
name = "hello-world-actix"
version = "0.1.0"
authors = ["boozmedina <boozmedina@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
actix = "0.10.0"
actix-web = "3.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.6.5", features = ["v4", "serde"] }
diesel = { version = "1.4.5", features = ["uuid", "r2d2", "postgres"] }
diesel_migrations = "1.4.0"
=======
actix-web = "3"
actix-rt = "2"
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = {version = "0.4", features = ["serde"]}
serde_json = "1.0"
serde = "1.0.125"
>>>>>>> 1d154780afa2e4a4e44e66b8da505d56fb22d65e
